ng_website/entry/urls.py
from django.conf.urls import include, url
from entry import views

# for namespace reverse url feature, see
# https://docs.djangoproject.com/en/1.10/topics/http/urls/#id4
app_name = 'entry'

urlpatterns = [
        url(
            r'^$',
            views.ListSwitcher.as_view(),
            name='list'
            ),
        url(
            r'^new$',
            views.CreateSwitcher.as_view(),
            name='new'
            ),
        url(
            r'^edit/(?P<pk>\d+)$',
            views.UpdateSwitcher.as_view(),
            name='edit'
            ),
        url(
            r'^delete/(?P<pk>\d+)$',
            views.DeleteSwitcher.as_view(),
            name='delete'
            ),
        url(
            r'^archive$',
            views.ListSwitcher.as_view(),
            kwargs={'archive': 'true'},
            name='archive'
            ),
        ]

ng_website/veranstaltungen/urls.py
from django.conf.urls import include, url
from veranstaltungen import views

# for namespace reverse url feature, see
# https://docs.djangoproject.com/en/1.10/topics/http/urls/#id4
app_name = 'veranstaltungen'

urlpatterns = [
        # url(
        #     r'^vorbei$',
        #     views.get_vergangene_veranstaltungen,
        #     name='vergangene'
        #     ),
        url(
            r'^anmeldung/(?P<eventid>\w+)$',
            views.get_anmeldung,
            name='anmeldung'
            ),
        url(
            r'^teilnehmende$',
            views.getTeilnehmende,
            name='teilnehmende'
            ),
        url(
            r'^teilnehmende/(?P<eventid>\w+)$',
            views.exportTeilnehmende,
            name='teilnehmende'
            ),
        url(
            r'^export/(?P<eventid>\w+)$',
            views.exportVeranstaltungen,
            name='export'
            ),
        url(
            r'^collect$',
            views.collect_veranstaltungen,
            name='collect'
            ),
        url(
            r'^accept$',
            views.accept_veranstaltungen,
            name='accept'
            ),
        url(
            r'^$',
            views.get_kommende_veranstaltungen,
            name='list'
            ),
        ]

ng_website/veranstaltungen/models.py
from django.db import models

# Create your models here.

ng_website/veranstaltungen/views.py
import datetime as dt
import unicodecsv as csv
from xml.etree import ElementTree as ET
from django.shortcuts import render
from django.core.cache import caches
from django.core.mail import send_mail, get_connection
from django.core.mail import EmailMultiAlternatives
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from .helper.form import Anmeldung
import django.http as http
from .helper.email_text_messages import email_message
from .helper import util
from .helper import buildHtml
from .helper import gCalAPI as calAPI
import settings

def get_kommende_veranstaltungen(request):
    if request.method == 'GET':
        todayHtml = [d for d in caches['veranstaltungen'].get('daily-html-list') if d[0] >= dt.date.today()]
        dayTupleList = [buildHtml.decorateVeranstaltungen(e) for e in todayHtml]
        monthlyHtml = [ET.tostring(x, encoding="unicode", method='html') for x in buildHtml.getMonthlyList(dayTupleList)]
        context = {
            'monthList': monthlyHtml,
            'category': 'veranstaltungen',
        }
        return render(request, 'veranstaltungen.html', context)

def exportVeranstaltungen(request, eventid=None):
    try:
        event = util.getEventFromCache(eventid)
    except IndexError:
        return http.HttpResponseBadRequest('<p>kein Zutritt.</p>')

    if request.method == 'GET':
        response = http.HttpResponse(event.get('ics'), content_type='text/calendar; charset=utf-8')
        response['Filename'] = 'event.ics'
        return response

def get_veranstaltungen(request):
    if request.method == 'GET':
        return render(request, 'veranstaltungen.html')

def collect_veranstaltungen(request):
    if request.method == 'GET' and request.user.is_staff:
        eventList = calAPI.getEventList()
        caches['veranstaltungen'].set('event_list', eventList, timeout=None)
        htmlList = buildHtml.generateHtmlList(eventList)
        caches['veranstaltungen'].set('daily-html-list-temporary', htmlList, timeout=None)
        todayHtml = [d for d in htmlList if d[0] >= dt.date.today()]
        dayTupleList = [buildHtml.decorateVeranstaltungen(e) for e in todayHtml]
        monthlyHtml = [ET.tostring(x, encoding="unicode", method='html') for x in buildHtml.getMonthlyList(dayTupleList)]
        context = {
            'monthList': monthlyHtml,
        }
        return render(request, 'veranstaltungen-test.html', context)
    else:
        return http.HttpResponseForbidden('<p>kein Zutritt.</p>')

def accept_veranstaltungen(request):
    if request.method == 'GET' and request.user.is_staff:
        buildHtml.publishTemporaryHtmlList()
        return redirect('veranstaltungen:list')
    else:
        return http.HttpResponseForbidden('<p>kein Zutritt.</p>')

def formatTeilnehmer(children, adults):
    if children > 0 and adults > 0:
        return "Kinder: {} und Erwachsene: {}".format(children, adults)
    elif children > 0:
        return "Kinder: {}".format(children)
    elif adults > 0:
        return "Erwachsene: {}".format(adults)
    return "Niemand?"

def getTeilnehmende(request):
    if (request.user.is_staff):
        eventHtmlList = buildHtml.handleTeilnehmende()
        context = {
            'eventList': eventHtmlList,
        }
        return render(request, 'teilnehmendeOverview.html', context)
    else:
        return http.HttpResponseForbidden('<p>kein Zutritt.</p>')

def exportTeilnehmende(request,eventid=None):
    if request.method == 'GET' and request.user.is_staff:
        tnList = caches['teilnehmende'].get(eventid, [])
        #TODO what if tnList == 0
        if len(tnList) > 0:
            response = http.HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="teilnehmer.csv"'
            fieldnames = ['fname', 'lname', 'email', 'phone', 'bemerkung',
                          'adultNumber', 'childrenNumber']
            writer = csv.DictWriter(response, fieldnames=fieldnames)
            writer.writeheader()
            [writer.writerow(i) for i in tnList]
            return response
    return http.HttpResponseForbidden('<p>kein Zutritt.</p>')

def get_anmeldung(request,eventid=None):
    try:
        event = util.getEventFromCache(eventid)
    except IndexError:
        return http.HttpResponseBadRequest('<p>keine Veranstaltung mit dieser ID gefunden. Bitte Veranstaltungen neu laden.</p>')
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = Anmeldung(request.POST)
        # check whether it's valid:
        if form.is_valid():
            data = {
                'fname': form.cleaned_data['sender_fname'],
                'lname': form.cleaned_data['sender_lname'],
                'childrenNumber': int(form.cleaned_data['childrenNumber']),
                'adultNumber': int(form.cleaned_data['adultNumber']),
                'email': form.cleaned_data['sender_email'],
                'phone': form.cleaned_data['sender_phone']
            }
            if len(form.cleaned_data['bemerkung']) > 3:
                data['bemerkung'] = form.cleaned_data['bemerkung']
            else:
                data['bemerkung'] = "Nichts"

            cacheList = caches['teilnehmende'].get(eventid, [])
            cacheList.append(data)
            # keep seven days after the end of event, have to remove tz, else error
            delta = event['end']['datetime'].replace(tzinfo=None) - dt.datetime.now() + dt.timedelta(days=7)
            caches['teilnehmende'].set(eventid, cacheList, delta.total_seconds())
            data['summary'] = event.get('summary')
            data['zeit'] = event.get('zeitRaw')
            data['teilnehmer'] = formatTeilnehmer(
                data['childrenNumber'], data['adultNumber']
            )

            message = email_message.format(**data)
            # sophisticated mail for customer because we want to attach ics 
            # to configure our own auth user/psw we have to pass a
            # 'connection' to EmailMessage. I copied this procedure from
            # send_mail()'s source code because send_mail() is a wrapped
            # EmailMessage.send() function.
            # site-packages/django/core/mail/__init__.py

            connection = get_connection(
                username="veranstaltungen@nuglargaerten.ch",
                password=settings.common.EMAIL_PASSWORD_VERANSTALTUNGEN,
                fail_silently=False,
            )
            # return mail.send()
            msg = EmailMessage(
                event.get('summary'),
                message,
                "veranstaltungen@nuglargaerten.ch",
                [
                    form.cleaned_data['sender_email'],
                    "veranstaltungen@nuglargaerten.ch",
                    "kontakt@nuglargaerten.ch",
                    "gartenzwerge@nuglargaerten.ch",
                    ],
                connection=connection
            )
            msg.attach('event.ics', event.get('ics'), 'text/calendar; charset=utf-8')
            # simple email, we dont want to send ics to ourselves
            try:
                msg.send()
            except Exception as e: print('Error while sending email: {}'.format(e))

            return render(
                request,
                'bestaetigung.html',
                {
                    'email': form.cleaned_data['sender_email'],
                    'name': form.cleaned_data['sender_fname'],
                    'category': 'veranstaltungen'
                }
            )
    else:
        form = Anmeldung()
    return render(
        request,
        'anmeldung.html',
        {
            'form': form,
            'category': 'veranstaltungen',
            'summary': event.get('summary'),
            'zeit': event.get('zeitRaw'),
        }
    )

ng_website/veranstaltungen/templates/anmeldung.html
{% extends "one-block.html" %}
{% load static %}
{% block one-block-content %}
<article>
  <hgroup class="title">
  <hr>
  <div class="main-title">
    <h2 class="g--12">
      Anmeldung für<span style="font-style: italic">{{summary}}<span>
    </h2>
  </div>
  <div class="sub-title g--12">
      {{zeit}}
  </div>
  <hr>
  </hgroup>

  <form class="veranstaltung anmeldung" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="formFieldWrapper">
      <h5>Dein Name <span class="required">*</span></h5> 
      <div class="isflex">
        <div class="g--4 g-t--12">
          <div class="g--12">
            <div class="form-input">
              {{ form.sender_fname.errors }}
              {{ form.sender_fname }}
            </div>
          </div>
          <div class="form-input">
            <div class="help-text"><i>{{ form.sender_fname.help_text|safe|escape }}</i></div>
          </div>
        </div>
        <div class="g--4 g-t--12">
          <div class="g--12">
            {{ form.sender_lname.errors }}
            {{ form.sender_lname }}
          </div>
          <div class="form-input">
            <div class="help-text"><i>{{ form.sender_lname.help_text|safe|escape }}</i></div>
          </div>
        </div>
      </div>
    </div>
    <div class="formFieldWrapper">
      <h5>Telefon <span class="required">*</span></h5>
      <div class="g--8 g-t--12">
        <div class="form-input">
          {{ form.sender_phone.errors }}
          {{ form.sender_phone }}
        </div>
      </div>
      <div class="form-input">
        <div class="help-text"><i>{{ form.sender_phone.help_text|safe|escape }}</i></div>
      </div>
    </div>
    <div class="formFieldWrapper">
      <h5>Email <span class="required">*</span></h5>
      <div class="g--8 g-t--12">
        <div class="form-input">
          {{ form.sender_email.errors }}
          {{ form.sender_email }}
        </div>
      </div>
      <div class="form-input">
        <div class="help-text"><i>{{ form.sender_email.help_text|safe|escape }}</i></div>
      </div>
    </div>
    <div class="formFieldWrapper">
      <h5>Wieviele Teilnehmende möchtest Du anmelden?<span class="required">*</span></h5>
      <div class="g--8 g-t--12 number-wrapper">
        <div class="g--1">
          {{ form.adultNumber.errors }}
          {{ form.adultNumber }}
        </div>
      </div>
      <div class="form-input g--8 g-t--12" style="margin-top:0.5rem">
        <div class="help-text"><i>{{ form.adultNumber.help_text|safe|escape }}</i></div>
      </div>
    </div>
    <div class="formFieldWrapper">
      <h5>Wieviele davon sind Kinder?</h5>
      <div class="g--8 g-t--12 number-wrapper">
        <div class="g--1">
          {{ form.childrenNumber.errors }}
          {{ form.childrenNumber }}
        </div>
      </div>
      <div class="form-input g--8 g-t--12" style="margin-top:0.5rem">
        <div class="help-text"><i>{{ form.childrenNumber.help_text|safe|escape }}</i></div>
      </div>
    </div>
    <div class="formFieldWrapper">
      <h5>Bemerkungen</h5>
      <div class="g--8 g-t--12">
        <div class="form-input">
          {{ form.bemerkung.errors }}
          {{ form.bemerkung }}
        </div>
      </div>
      <div class="form-input">
        <div class="help-text"><i>{{ form.bemerkung.help_text|safe|escape }}</i></div>
      </div>
    </div>
    <input
      class="btn--raised btn--green"
      type="submit"
      value="Verbindlich anmelden" />
  </form>
</article>
{% endblock %}

ng_website/veranstaltungen/templates/bestaetigung.html
{% extends "one-block.html" %}
{% load static %}
{% block one-block-content %}
<article>
  <hgroup class="title">
    <hr>
    <div class="main-title">
      <h2>
        Herzlichen Dank für die Anmeldung, {{fname}}!
      </h2>
    </div>
    <hr>
  </hgroup>
  Wir haben eine Bestätigung an {{ email }} geschickt. Falls sie nicht angekommen (bitte auch im Spam nachschauen) ist oder andere Fragen auftauchen, kontaktiere bitte
  <a href="mailto:veranstaltungen@nuglargaerten.ch"> veranstaltungen@nuglargaerten.ch </a>.
</article>
{% endblock %}

ng_website/veranstaltungen/templates/einleitung.html
<div class="monat reihe einleitung">
  <div class="tag reihe">
    <div class="tag label"></div>
    <div class="alle kategorien">
      <div class="g-t--12 g--4 kategorie gemeinschaft">
        <div>
          <label class="label start end event">
            Gemeinschaft
          </label>
        </div>
      </div>
      <div class="g-t--12 g--4 kategorie bildung">
        <div>
          <label class="label start end event">
            Bildung
          </label>
        </div>
      </div>
      <div class="g-t--12 g--4 kategorie landwirtschaft">
        <div>
          <label class="label event start end">
            Landwirtschaft
          </label>
        </div>
      </div>
      <p>
        Neben der Landwirtschaft ist uns die Gemeinschaft sowie die Bildung
        wichtig. Du bist herzlich eingeladen an unserem bunten Programm
        teilzunehmen. Bitte jeweils Anmelden: Mit dem Formular bei der
        Veranstaltung oder unter
        veranstaltungen@nuglargaerten.ch<mailto:veranstaltungen@nuglargaerten.ch> 
      </p>
    </div>
  </div>
</div>

ng_website/veranstaltungen/templates/hevent.html
<div>
	<label class="label event summary {{classes}}" for="{{eventid}}">{{summary}}</label>
	<div class="overlay background" id="{{eventid}}">
		<div class="g-m--12 g--8 overlay h-event">
      <div class="overlay titlebar">
        <button class="btn close-detail btn--round transparent" >
          <i class="fa fa-close"></i>
        </button>
      </div>
			<div class="overlay row">
				<i class="fa fa-calendar g--1" aria-hidden="true"></i>
				<h2>{{summary}}</h2>
			</div>
			<hr />
			<div class="overlay row">
				<i class="fa fa-clock-o g--1" aria-hidden="true"></i>
				<div class="zeit container">
					<span class="zeit">
						{% autoescape off %}
						{{zeit}}
						{% endautoescape %}
					</span>
				</div>
			</div>
			{% if location != '' %}
			<div class="overlay row">
				<i class="fa fa-map-marker g--1" aria-hidden="true"></i>
				<div class="time container">
					<span class="ort">{{location}}</span>
				</div>
			</div>
			{% endif %}
			{% if description != 'None' %}
			<div class="overlay row description"><p>
					{% autoescape off %}
					{{description}}
					{% endautoescape %}
				</p>
			</div>
			{% endif %}
			<div class="overlay row button">
				<a class="btn btn--flat" href="{% url 'veranstaltungen:anmeldung' eventid %}">Ich möchte mich anmelden</a>
				<a class="btn btn--flat " href="{% url 'veranstaltungen:export' eventid %}">Meinem Kalender hizufügen</a>
			</div>
		</div>
	</div>
</div>

ng_website/veranstaltungen/templates/teilnehmende.html
<div class="teilnehmende overview event {{kategorie}} opaque">
  <div class="teilnehmende event row {{classes}}"
       {% if anzahl > 0 %}
       onclick="showoverlay('{{eventid}}')"
       {% endif %}
       >
       <div class="g--2"> {{ start.dateDisplayDe }} </div>
       <div class="g--9"> {{ summary }} </div>
       <div> {{ anzahl }} </div>
  </div>
  <div class="overlay background" id="{{eventid}}">
    <div class="g-m--12 g--8 overlay {{kategorie}} opaque">
      <div class="overlay titlebar">
        <button
          onclick="closeoverlay('{{eventid}}')"
          name="close attendees of event window"
          type="button"
          class="btn close-detail btn--round transparent" >
          <i class="fa fa-close"></i>
        </button>
      </div>
      <div class="overlay row">
        <table>
          <tr>
            <th>Vorname</th> <th>Nachname</th>
            <th>Email</th><th>Telefonnummer</th>
            <th>Anzahl Teilnehmer</th><th>Davon Kinder</th>
            <th>Bemerkung</th>
          </tr>
          {% for t in teilnehmende %}
          <tr>
            <td>{{t.fname}}</td><td>{{t.lname}}</td>
            <td>{{t.email}}</td><td>{{t.phone}}</td>
            <td>{{t.adultNumber}}</td><td>{{t.childrenNumber}}</td>
            <td>{{t.bemerkung}}</td>
          </tr>
          {% endfor %}
        </table>
      </div>
      <div class="overlay row button">
        <a class="btn btn--flat " href="{% url 'veranstaltungen:teilnehmende' eventid %}">CSV herunterladen</a>
      </div>
    </div>
  </div>
</div>

ng_website/veranstaltungen/templates/teilnehmendeOverview.html
{% extends "base.html" %}
{% block content %}
<section class="g--8 g-t--12">
  <article class="calendar">
    <div class="teilnehmende container">
      {% for event in eventList %}
      {% autoescape off %}
      {{ event }}
      {% endautoescape %}
      {% endfor %}
    </div>
  </article>
</section>
{% endblock %}

ng_website/veranstaltungen/templates/veranstaltungen-test.html
{% extends "base.html" %}
{% block content %}
<section class="g--8 g-t--12">
  <article class="calendar">
    <div class="monat reihe einleitung">
      <div class="alle kategorien tag reihe">
        Bitte schaue, ob die Änderungen korrekt übernommen wurden und drücke auf
        den entsprechenden Knopf. Falls etwas schiefgelaufen ist, bitte bei
        Cristoffel melden.
        <div class="overlay row button teilnehmende">
          <a class="btn btn--flat" href="{% url 'veranstaltungen:accept' %}">Ist gut so!</a>
          <a class="btn btn--flat" href="{% url 'veranstaltungen:list' %}">Nein, abbrechen!</a>
        </div>
      </div>
    </div>
    <div class="veranstaltungen container kommend">
      {% include "einleitung.html" %}
      {% for month in monthList %}
      {% autoescape off %}
      {{ month }}
      {% endautoescape %}
      {% endfor %}
    </div>
  </article>
</section>
{% endblock %}

ng_website/veranstaltungen/templates/veranstaltungen.html
{% extends "base.html" %}
{% block content %}
<section class="g--8 g-t--12">
  <article class="calendar">
    {% if request.user.is_staff %}
    <div class="overlay row button teilnehmende">
      <a class="btn btn--flat" href="{% url 'veranstaltungen:teilnehmende' %}">Liste mit Teilnehmenden anzeigen</a>
      <a class="btn btn--flat" href="{% url 'veranstaltungen:collect' %}">Veranstaltungen aktualisieren (geht ein paar Sekunden)</a>
    </div>
    {% endif %}
    <div class="veranstaltungen container kommend">
        {% include "einleitung.html" %}
        {% for month in monthList %}
        {% autoescape off %}
        {{ month }}
        {% endautoescape %}
        {% endfor %}
    </div>
  </article>
</section>
{% endblock %}