ng_website/entry/urls.py
from django.conf.urls import include, url
from entry import views

# for namespace reverse url feature, see
# https://docs.djangoproject.com/en/1.10/topics/http/urls/#id4
app_name = 'entry'

urlpatterns = [
        url(
            r'^$',
            views.ListSwitcher.as_view(),
            name='list'
            ),
        url(
            r'^new$',
            views.CreateSwitcher.as_view(),
            name='new'
            ),
        url(
            r'^edit/(?P<pk>\d+)$',
            views.UpdateSwitcher.as_view(),
            name='edit'
            ),
        url(
            r'^delete/(?P<pk>\d+)$',
            views.DeleteSwitcher.as_view(),
            name='delete'
            ),
        url(
            r'^archive$',
            views.ListSwitcher.as_view(),
            kwargs={'archive': 'true'},
            name='archive'
            ),
        ]

ng_website/ng_website/urls.py
"""ng_website URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
"""
from django.conf.urls import include, url
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views
from django.contrib import admin, auth
from django.conf import settings
import ackerpatenschaft.views as ackerpatenschaftViews
import newsletter.views as nlview

urlpatterns = [
        url(
            r'^solila/',
            include('entry.urls', namespace='solila',),
            {'category': 'solila'}
            ),

        url(
            r'^angebote/',
            include('entry.urls', namespace='angebote',),
            {'category': 'angebote'}
            ),

        url(
            r'^ernte-abo/',
            include('entry.urls', namespace='ernte-abo',),
            {'category': 'ernte-abo'}
            ),

        url(
            r'^blog/',
            include('entry.urls', namespace='blog',),
            {'category': 'blog'}
            ),

        url(
            r'^rezept/',
            include('entry.urls', namespace='rezept',),
            {'category': 'rezept'}
            ),

        url(
            r'^lernort/',
            include('entry.urls', namespace='lernort',),
            {'category': 'lernort'}
            ),


        url(
            r'^policy/',
            include('entry.urls', namespace='policy',),
            {'category': 'policy'}
            ),

        url(
            r'^mitwirken/',
            include('entry.urls', namespace='mitwirken',),
            {'category': 'mitwirken'}
            ),

        url(
            r'^danggerscheen/',
            include('entry.urls', namespace='danggerscheen',),
            {'category': 'danggerscheen'}
            ),

        url(
            r'^veranstaltungen/',
            include('veranstaltungen.urls', namespace='veranstaltungen'),
            ),

        url(
            r'^ackerpatenschaft',
            ackerpatenschaftViews.get_ackerpatenschaft,
            ),
        url(
            r'^newsletter',
            nlview.get_nlregistration,
            ),

        url(r'^admin/', admin.site.urls),
        url(r'^accounts/', include('allauth.urls')),
        url(r'^auth/', include('django.contrib.auth.urls')),
        url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html')),
        url(r'^kalender/', RedirectView.as_view(url='/veranstaltungen', permanent=True), name='redirect-to-veranstaltungen'),
        url(
            r'^',
            include('entry.urls', namespace='home'),
            {'category': 'home'}
            ),
        ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
            ] + urlpatterns

ng_website/templates/base.html
{% load static socialaccount account %}
<!doctype html>
<html>
  {% include "head.html" %}
  <body class="cd-fixed-bg">
    <input type="checkbox" class="nav-main" id="nav-main-responsive">
    {% include "nav.html" %}
    <header class="ng-header">
      <div>
        <label class="nav-main" for="nav-main-responsive"><i class="fa fa-bars fa-lg"></i></label>
      </div>
      <div class="sonne" class="g--8 no-margin">
        <nav role="navigation">
          <ul id="abo-nav-container">
            <li>
                    <!-- <a href="{% url 'veranstaltungen:list' %}"> -->
              <a href="{% url 'angebote:list' %}">
                <div id="sonne"
                    <div id="sonne-innen"
                         {% comment %}
                         {% if category == 'veranstaltungen'  %}
                         {% endcomment %}
                         {% if category == 'angebote'  %}
                        class="active"
                         {% endif %}
                    >
                  <div id="sonne-innen"
                    {% comment %}
                      {% if category == 'veranstaltungen'  %}
                    {% endcomment %}
                    {% if category == 'angebote'  %}
                      class="active"
                    {% endif %}
                      ><p>Ernte-Abo</p></div>
                  <!-- ><p>Kalender</p></div> -->
                </div>
              </a>
            </li>
          </ul>
        </nav>
      </div>
    </header>
    <main class="ng-body g--12">
      {% if category == 'home' %}
      <section class="g--8 g-t--12 welcome">
        <div class="g--5 circle-box logo">
          <div class="circle-inner">
            <img alt="Nuglar Gärten" src="{% static 'img/logo_text.png' %}">
          </div>
        </div>
        <i id="scroll-indicator" class="fa fa-arrow-circle-down fa-lg"></i>
      </section>
      {% endif %}
      {% block content %}
      {% endblock %}
      <footer class="g--8 g-t--12">
        <address class="g--3 g-m--6">
          <h6>Nuglar Gärten</h6>
          <div class="footer-box">
            <span class="co">c/o Dominique Oser</span><br>
            <span class="street">Oberdorfstrasse 73</span><br>
            <span class="postal-code">4412 Nuglar</span><br>
            <span class="email">
              <a href="mailto:kontakt@nuglargaerten.ch">
                kontakt@nuglargaerten.ch
              </a>
            </span>
          </div>
        </address>
        <section class="phone g--3 g-m--6">
          <div style="display: flex;">
            <i style="vertical-align: baseline" class="fa fa-phone" aria-hidden="true"></i>
						<span style="margin-left: 0.5rem; vertical-align: baseline">
              Benjamin:
            </span>
          </div>
          <div class="footer-box">
                <span class="phone">
                  <a href"tel:+415280492">
                    077 528 04 92
                  </a>
                </span>
            <table>
              <tr>
                <td>Mo&Di</td><td>09h-17h</td>
              </tr>
              <tr>
                <td>Do</td><td>09h-17h</td>
              </tr>
              <tr>
                <td>Fr</td><td>09h-12h</td>
              </tr>
            </table>
          </div>
          </div>
        </section>
        <section class="bank-account g--5 g-m--11">
          <h6>Kontoangaben</h6>
          <div class="footer-box bank-account-switch">
            <input class="tabbed" type="radio" name="tabs" id="tab1" checked />
            <label for="tab1">Spendenkonto</label>
            <input class="tabbed" type="radio" name="tabs" id="tab2" />
            <label for="tab2">Konto Zahlungen</label>
            <div class="tab content1">
                <div class="client">Fördergem. f. e. sinnst. Wandel in der Landwirtschaft</div>
                <div class="bank">Freie Gemeinschaftsbank, 4001 Basel</div>
                <div class="iban">IBAN: CH19 0839 2000 1564 3630 2</div>
            </div>
            <div class="tab content2">
                <div class="client">Verein Nuglar Gärten, 4412 St. Pantaleon</div>
                <div class="bank">Freie Gemeinschaftsbank, 4001 Basel</div>
                <div class="iban"> IBAN: CH42 0839 2000 1517 0131 8</div>
            </div>
          </div>
        </section>
        <section class="icons g--1 g-m--1">
          <div class="fb">
            <a href="https://www.facebook.com/nuglargaerten">
              <i class="fa fa-facebook-square" aria-hidden="true"></i>
            </a>
          </div>
          <div class="danggerscheen">
            <a href="{% url 'danggerscheen:list' %}">
              <i class="fa fa-gift"></i>
            </a>
          </div>
          <div class="user-info">
            {% if user.is_authenticated %}
            <span>Du bist: {% user_display user %}</span>
            <a href="{% url 'logout' %}?next={{ request.path }}">
              <i class="fa fa-sign-out"></i>
            </a>
            {% else %}
            <a href="{% provider_login_url 'google' %}?next={{ request.path }}"><i class="fa fa-sign-in"></i></a>
            {% endif %}
          </div>
        </section>
      </footer>
    </main>
  </body>
</html>

ng_website/templates/head.html
{% load static bg_img %}

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>
    {% block title %}
    Nuglar Gärten
    {% endblock %}
  </title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Homepage der Nuglar Gärten">
  <meta name="author" content="cricri">
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <link rel="apple-touch-icon" type="image/png"
  href="{% static 'img/favicon.ico' %}">
  <link rel="shortcut icon" type="image/png"
  href="{% static 'img/favicon.ico' %}"/>

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->


  {% block css %}
  <!-- This file stores project-specific CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
  {% endblock %}

  <style> 

.cd-fixed-bg {
  min-height: 100vh;
  background-size: cover;
  background-color: rgb(255,247,233);
  background-attachment: fixed;
  background-repeat: no-repeat;
  background-position: center center;
  scroll-behavior: smooth;
}

  @media screen and (max-width: 576px) {
    #nav-main {
      min-height: 100vh;
      background-size: cover;
      background-attachment: fixed;
      background-repeat: no-repeat;
      background-position: center center;
      background-image: url({% get_bg_img_url "small" %})
    }
  }
  @media screen and (orientation:portrait) {
    @media (max-height: 576px) {
      .cd-fixed-bg {
        background-image: url({% get_bg_img_url "small" %})
      }
    }
    @media (min-height: 577px) and (max-height: 900px) {
      .cd-fixed-bg {
        background-image: url({% get_bg_img_url "medium" %})
      }
    }
    @media (min-height: 901px) and (max-height: 1152px) {
      .cd-fixed-bg {
        background-image: url({% get_bg_img_url "big" %})
      }
    }
    @media (min-height: 1153px) {
      .cd-fixed-bg {
        background-image: url({% get_bg_img_url "huge" %})
      }
    }
  }
  @media screen and (orientation:landscape) {
    @media (max-width: 1024px) {
      .cd-fixed-bg {
        background-image: url({% get_bg_img_url "small" %})
      }
    }
    @media (min-width: 1025px) and (max-width: 1600px) {
      .cd-fixed-bg {
        background-image: url({% get_bg_img_url "medium" %})
      }
    }
    @media (min-width: 1601px) and (max-width: 2048px) {
      .cd-fixed-bg {
        background-image: url({% get_bg_img_url "big" %})
      }
    }
    @media (min-width: 2049px) {
      .cd-fixed-bg {
        background-image: url({% get_bg_img_url "huge" %})
      }
    }
  }
  </style>
<script type="text/javascript" src="{% static 'js/zoom_image.js' %}"></script>
</head>

ng_website/templates/login.html
{% extends "one-block.html" %}
{% block one-block-content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

ng_website/templates/nav-collapsible.html
{% load tags %}
{% url collap_category|add:':list' as the_url %}
{% get_category_list all_objects collap_category as elist %}
<li class="
           {% if category == collap_category %} active {% endif %}
    ">
    {% if elist|length > 1 and collap_category != "rezept" %}
        {% if category == collap_category %}
            <input type="checkbox" id="collapsible-{{collap_category}}">
        {% else %}
            <input type="checkbox" id="collapsible-{{collap_category}}" checked>
        {% endif %}
        <div class="collapsible-label-wrapper">
            <a href="{{ the_url }}">
                {{title}}
            </a>
            <label for="collapsible-{{collap_category}}"><i class="fa fa-angle-double-left fa-lg"></i></label>
        </div>
        <ul class="collapsible-{{collap_category}}-area">
            {% for entry in elist %}
            <li>
                <a href="{{ the_url }}#{{entry.title|urlencode}}">{{entry.title}}</a>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <a href="{{ the_url }}">
            {{title}}
        </a>
    {% endif %}
</li>

ng_website/templates/nav.html
{% load static tags %}
<nav id="nav-main" class="g--2 g-s--3 g-m--3 g-t--12" role="navigation">
    <div class="nav-logo">
        <div class="g--4 logo circle-box {% if category == 'home'  %} active {% endif %}">
            <a href="{% url 'home:list' %}">
                <div class="circle-inner">
                    <img src="{% static 'img/logo_keimling.png' %}">
                </div>
            </a>
        </div>
    </div>
    <ul>
        {% include "nav-collapsible.html" with collap_category="solila" title="SoliLa" %}
        {% include "nav-collapsible.html" with collap_category="angebote" title="Angebote" %}
        <li class="
                   {% if category == 'blog' %} active {% endif %}
                   {% if collap_category == 'veranstaltungen' %} sonne {% endif %}
            ">
            {% if category == 'blog' or category == 'veranstaltungen' %}
            <input type="checkbox" id="collapsible-blog">
            {% else %}
            <input type="checkbox" id="collapsible-blog" checked>
            {% endif %}
            <div class="collapsible-label-wrapper">
                <a href="/blog">
                    Aktuelles
                </a>
                <label for="collapsible-blog">
                    <i class="fa fa-angle-double-left fa-lg"></i>
                </label>
            </div>
            <ul class="collapsible-blog-area">
                <li>
                    <a href="/blog">Blog</a>
                </li>
                <li>
                    <a href="/veranstaltungen">Kalender</a>
                </li>
            </ul>
        </li>
        {% include "nav-collapsible.html" with collap_category="mitwirken" title="Mitwirken" %}
        {% include "nav-collapsible.html" with collap_category="rezept" title="Rezepte" %}
        {% include "nav-collapsible.html" with collap_category="lernort" title="Lernort" %}
    </ul>
</nav>

ng_website/templates/one-block.html
{% extends "base.html" %}
{% block content %}
<section class="g--8 g-t--12" id="entry-container">
  {% block one-block-content %}{% endblock %}
</section>
{% endblock %}