ng_website/entry/urls.py
from django.conf.urls import include, url
from entry import views

# for namespace reverse url feature, see
# https://docs.djangoproject.com/en/1.10/topics/http/urls/#id4
app_name = 'entry'

urlpatterns = [
        url(
            r'^$',
            views.ListSwitcher.as_view(),
            name='list'
            ),
        url(
            r'^new$',
            views.CreateSwitcher.as_view(),
            name='new'
            ),
        url(
            r'^edit/(?P<pk>\d+)$',
            views.UpdateSwitcher.as_view(),
            name='edit'
            ),
        url(
            r'^delete/(?P<pk>\d+)$',
            views.DeleteSwitcher.as_view(),
            name='delete'
            ),
        url(
            r'^archive$',
            views.ListSwitcher.as_view(),
            kwargs={'archive': 'true'},
            name='archive'
            ),
        ]

ng_website/entry/models.py
# coding: utf8
from django.db import models
from django.urls import reverse
from datetime import date

class BaseEntry(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(
            default='',
            help_text=(
                "Der Text kann mit Markdown formatiert werden. "
                "Eine Anleitung zu Markdown gibt's "
                "<a href='https://github.com/adam-p/markdown-here/"
                "wiki/Markdown-Cheatsheet'>hier</a>."
                )
            )
    order = models.PositiveIntegerField(
            default=100,
            help_text=(
                "Die Einträge werden nach dieser Nummer sortiert. Zu oberst "
                "erscheint der Eintrag mit der kleinsten Nummer."
                )
            )

    class Meta:
        abstract = True
        ordering = ['order']

    def __unicode__(self):
        return self.title


class Entry(BaseEntry):
    CATEGORIES = (
        ('home', 'home'),
        ('solila', 'solila'),
        ('mitwirken', 'mitwirken'),
        ('lernort', 'lernort'),
        ('ernte-abo', 'ernte-abo'),
    )

    category = models.CharField(
        max_length=16, choices = CATEGORIES,
    )


class Blog(BaseEntry):
    publishDate = models.DateField(default=date.today)

    class Meta:
        ordering = ['-publishDate']


class Kalender(BaseEntry):
    coordinates = models.CharField(
            max_length=200,
            blank=True,
            help_text=(
                "Wann und wo findet der Event statt?" 
                )
            )
    startDate = models.DateField(
            default=date.today,
            help_text=(
                "Wann beginnt der Event? Kalendereintrage werden nach diesem "
                "Datum sortiert."
                )
            )
    endDate = models.DateField(
            null=True, blank=True,
            help_text=(
                "Wann soll der Event aus dem Kalender verschwinden? Der "
                "Kalendereintrag wird ab diesem Datum nicht mehr angezeigt."
                "Kann auch leer gelassen werden. In dem Fall verschwindet "
                "der Eintrag nach Ablauf der Startdatums."
                )
            )
    class Meta:
        ordering = ['startDate']

ng_website/entry/views.py
from django.views.generic import View, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from datetime import date

from entry.models import Entry, Blog, Kalender

genericFields = ['title', 'order', 'content']
kalenderFields = ['title', 'coordinates', 'startDate', 'endDate', 'content']
blogFields = ['title', 'publishDate', 'content']

def reverse_url_func(category):
    return reverse_lazy('%s:list' % category)

class BaseList(TemplateView):
    success_url = reverse_lazy('entry:list')
    breadcumbs = ['list']
    template_name = 'entry/entry_list.html'


class GenericList(BaseList):
    model = Entry
    category = ''
    def get_context_data(self, **kwargs):
        context = super(GenericList, self).get_context_data(**kwargs)
        # get url namespace and attach it to the context
        context['entry_list'] = Entry.objects.all().filter(
                category=self.category
                )
        return context


class KalenderList(BaseList):
    model = Kalender
    def get_context_data(self, **kwargs):
        context = super(KalenderList, self).get_context_data(**kwargs)
        # get url namespace and attach it to the context
        context['entry_list'] = (
                Kalender
                .objects
                .all()
                .filter(Q(startDate__gte=date.today()) | Q(endDate__gte=date.today()))
                )
        return context


class BlogList(BaseList):
    model = Blog
    def get_context_data(self, **kwargs):
        context = super(BlogList, self).get_context_data(**kwargs)
        # get url namespace and attach it to the context
        if kwargs.get('archive'):
            context['entry_list'] = Blog.objects.all()[5:]
        else:
            context['entry_list'] = Blog.objects.all()[:5]
        return context


class ListSwitcher(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        if kwargs.get('category') == 'kalender':
            return KalenderList.as_view()(request, *args, **kwargs)
        elif kwargs.get('category') == 'blog':
            return BlogList.as_view()(request, *args, **kwargs)
        else:
            return GenericList.as_view(
                    category=kwargs.get('category')
                    )(request, *args, **kwargs)


class BaseCreate(PermissionRequiredMixin, CreateView):
    template_name = 'entry/entry_form.html'


class GenericCreate(BaseCreate):
    model = Entry
    fields = genericFields
    category = ''
    permission_required = 'entry.add_entry'
    def form_valid(self, form):
        # automatically assign category to model instance
        form.instance.category = self.category
        return super(GenericCreate, self).form_valid(form)


class KalenderCreate(BaseCreate):
    model = Kalender
    fields = kalenderFields
    success_url = reverse_lazy('kalender:list')
    permission_required = 'entry.add_kalender'
    pass


class BlogCreate(BaseCreate):
    model = Blog
    fields = blogFields
    success_url = reverse_lazy('blog:list')
    permission_required = 'entry.add_blog'
    pass


class CreateSwitcher(CreateView):
    def dispatch(self, request, *args, **kwargs):
        cat = kwargs.get('category')
        if cat == 'kalender':
            return KalenderCreate.as_view(
                    success_url = reverse_url_func(cat)
                    )(request, *args, **kwargs)
        elif cat == 'blog':
            return BlogCreate.as_view(
                    success_url = reverse_url_func(cat)
                    )(request, *args, **kwargs)
        else:
            cat = kwargs.get('category')
            return GenericCreate.as_view(
                    category = cat,
                    success_url = reverse_url_func(cat)
                    )(request, *args, **kwargs)


class BaseUpdate(PermissionRequiredMixin, UpdateView):
    template_name = 'entry/entry_form.html'


class GenericUpdate(BaseUpdate):
    model = Entry
    fields = genericFields
    category = ''
    permission_required = 'entry.change_entry'
    pass


class KalenderUpdate(BaseUpdate):
    model = Kalender
    fields = kalenderFields
    permission_required = 'entry.change_kalender'
    pass


class BlogUpdate(BaseUpdate):
    model = Blog
    fields = blogFields
    permission_required = 'entry.change_blog'
    pass


class UpdateSwitcher(UpdateView):
    def dispatch(self, request, *args, **kwargs):
        cat = kwargs.get('category')
        if cat == 'kalender':
            return KalenderUpdate.as_view(
                    success_url = reverse_url_func(cat)
                    )(request, *args, **kwargs)
        elif cat == 'blog':
            return BlogUpdate.as_view(
                    success_url = reverse_url_func(cat)
                    )(request, *args, **kwargs)
        else:
            return GenericUpdate.as_view(
                    category=cat,
                    success_url = reverse_url_func(cat)
                    )(request, *args, **kwargs)


class BaseDelete(PermissionRequiredMixin, DeleteView):
    model = Entry
    template_name = 'entry/entry_confirm_delete.html'
    permission_required = 'entry.delete_entry'


class KalenderDelete(BaseDelete):
    model = Kalender
    permission_required = 'entry.delete_kalender'
    pass


class BlogDelete(BaseDelete):
    model = Blog
    permission_required = 'entry.delete_blog'
    pass


class DeleteSwitcher(DeleteView):
    def dispatch(self, request, *args, **kwargs):
        cat = kwargs.get('category')
        if cat == 'kalender':
            return KalenderDelete.as_view(
                    success_url = reverse_url_func(cat)
                    )(request, *args, **kwargs)
        elif cat == 'blog':
            return BlogDelete.as_view(
                    success_url = reverse_url_func(cat)
                    )(request, *args, **kwargs)
        else:
            return BaseDelete.as_view(
                    success_url = reverse_url_func(cat)
                    )(request, *args, **kwargs)

ng_website/entry/templates/entry/entry_confirm_delete.html
{% extends "one-block.html" %}
{% block one-block-content %}
<article>
  <form method="post">{% csrf_token %}
    Are you sure you want to delete entry "{{ object }}" ?
    <input class="btn--raised btn--red right" type="submit" value="Delete" />
  </form>
</article>
{% endblock %}

ng_website/entry/templates/entry/entry_form.html
{% extends "one-block.html" %}
{% load static  %}
{% block one-block-content %}
<article>
  <form method="post">{% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="formFieldWrapper {{ field.name }}">
      {{ field.errors }}
      <label class="g--12 no-margin" for="{{ field.id_for_label }}">
        <h4 style="display:inline;"> {{ field.name }}</h4>
      </label>
      <hr> 
      <div class="form-input">
        <div class="help-text"><i>{{ field.help_text|safe|escape }}</i></div>
        {{ field }}
      </div>
    </div>
    {% endfor %}
    <hr>
    <input class="btn--raised btn--green" type="submit" value="Submit" />
    <a class="btn--raised btn--red right" href="{% url 'entry:list' %}">
      Cancel
    </a>
  </form>
</article>
{{ form.media }}
{% endblock %}

ng_website/entry/templates/entry/entry_list.html
{% extends "one-block.html" %}
{% load static %}
{% block one-block-content %}

{% for entry in entry_list %}
  {% include "entry/entry_single.html" %}
{% endfor %}
{% if category == "blog" and not archive %}
<article>
    Mehr davon gibt's im <a href="/blog/archive">Archiv</a>.
</article>
{% endif %}
{% if perms.entry %}
<div class="new-entry-button">
  <a href="{% url 'entry:new' %}">
    <button class="btn--float color--white btn--green">+</button>
  </a>
</div>
{% endif %}
<div id="div-zoom-overlay">
  <img id="img-zoom-overlay" />
</div>
{% endblock %}

ng_website/entry/templates/entry/entry_single.html
{% load static tags %}
<article>
  <hgroup id="{{entry.title}}" class="title">
    <hr>
    <div class="main-title">
      <h2> {{entry.title}} </h2>
      {% if perms.entry %}
      <div>
        <a class="btn--raised btn--red"
          href="{% url 'entry:delete' entry.id %}">
          delete
        </a>
        <a class="btn--raised btn--blue"
          href="{% url 'entry:edit' entry.id %}">
          edit
        </a>
      </div>
      {% endif %}

    </div>
    <h4 class="sub-title">
      {% if entry.coordinates %}
      {{entry.coordinates}}
      {% elif entry.publishDate %}
      {{entry.publishDate}}
      {% endif %}
    </h4>
    <hr>
  </hgroup>
  <div class="article-body">
    {% autoescape off %}
    {% md_to_html entry.content %}
    {% endautoescape %}
  </div>
</article>